version: '2'
services:
  app:
    image: ruby:2.3.1
    working_dir: /usr/src/app
    environment:
      TMPDIR: /usr/src/app/tmp
      BUNDLE_PATH: /usr/src/app/.bundle
      BUNDLE_CONFIG: /usr/src/app/bundle/config
      BIGQUERY_KEYFILE: "/etc/app/keyfile.json"
      BIGQUERY_PROJECT: "--replace-me--"
    volumes:
      - .:/usr/src/app
      - ./etc/:/etc/app/



